openapi: 3.0.3
info:
  title: BattleReadyShelf API
  version: 0.1.0
  description: BattleReadyShelf API
servers:
  - url: /
paths:
  /api/v1/army-collections:
    get:
      tags: [ "ArmyCollections" ]
      summary: Get all army collections
      operationId: getArmyCollections
      responses:
        '200':
          description: A list of army collections
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArmyCollection'
              example:
                - id: "11111111-1111-1111-1111-111111111111"
                  name: "Starter Collection"
                  description: "An example collection"
    post:
      tags: [ "ArmyCollections" ]
      summary: Create a new army collection
      operationId: createArmyCollection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArmyCollection'
      responses:
        '201':
          description: Created army collections
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArmyCollection'
components:
  schemas:
    ArmyCollection:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        description:
          type: string
      required: [ name ]
