spring:
  profiles:
    active: local
  application:
    name: battlereadyshelf
  mvc:
    servlet:
      path: /battlereadyshelf
  flyway:
    schemas: battlereadyshelf
    default-schema: battlereadyshelf
    create-schemas: true
    baseline-on-migrate: false
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: battlereadyshelf
google:
  oauth:
    client-id: 421501872179-iatsrrehua5g62ot3j4gtv9qv9pghc3m.apps.googleusercontent.com
battlereadyshelf:
  superadmin:
    email: ${SUPERADMIN_EMAIL}